---
  - 
    end: 
      latitude: 58.211678
      elevation: 43
      longitude: 8.095269
    localizer: 
      elevation: 43
      longitude: 8.096228
      frequency: 110300
      latitude: 58.212397
      heading: 36
      beam_width: 4.5
    glideslope: 
      latitude: 58.198664
      angle: 3.4
      elevation: 39
      longitude: 8.080164
      threshold_distance: 720
    start: 
      latitude: 58.196703
      elevation: 26
      longitude: 8.075406
    magnetic_heading: 33.9
    strip: 
      width: 147
      length: 6660
      id: 4064
      surface: "ASP"
    identifier: "04"
    id: 8127
  - 
    end: 
      latitude: 60.216092
      elevation: 682
      longitude: 11.091397
    localizer: 
      elevation: 686
      longitude: 11.093536
      frequency: 110300
      latitude: 60.219775
      heading: 16
      beam_width: 4.5
    glideslope: 
      latitude: 60.187694
      angle: 3
      elevation: 669
      longitude: 11.072715
      threshold_distance: 943
    start: 
      latitude: 60.185019
      elevation: 650
      longitude: 11.073491
    magnetic_heading: 13.7
    strip: 
      width: 147
      length: 11811
      id: 4076
      surface: "ASP"
    identifier: "01L"
    id: 8151
  - 
    end: 
      latitude: 31.986566548174867
      elevation: 82
      longitude: 44.4195410531566
    start: 
      latitude: 31.99310459553514
      elevation: 103
      longitude: 44.388960932540336
    magnetic_heading: 96.6
    strip: 
      width: 150
      length: 9800
      id: 12085
      surface: "Asphalt"
    identifier: "10"
    id: 19435